### ISSUE TITLE
A question about projected point in the Poincar’e ball 

### ISSUE THREAD

**Issue by 1seyana1** [JHome1/Hyper-AVZL#1]
At the beginning of the third paragraph（3. Preliminary), You mentioned perform the hyperbolic projection to constrain the embeddings.I was wondering how you implemented this in your code.

Thank you for your attention

**Comment by JHome1** [comment]
Thanks a lot for your question! The projections are reflected from line 501 to 550 in ```./src
/model_improvements.py```.
